NUMPY

In [36]:
#Create a 1D array from a list

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [37]:
#Create a 3*3 array of zeros
zeros_arr = np.zeros((3, 3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
#Create a 2*2 array of zeros

arr=np.ones((2,2))

print(arr)

[[1. 1.]
 [1. 1.]]


In [39]:
#Generate array from 0 to 10(exclusive)
arr = np.arange(0, 10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#Create 5 evenly spaced numbers between 0 and 1

arr=np.linspace(0,1,5)

print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [41]:
#Create a 4*4 identity matrix

arr=np.eye(4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
#Reshape 1D array to 2D 
arr = arr.reshape(2, 8)
print(arr)



[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]


In [43]:
# Get the shape and dtype of an array
arr=np.array([1,2,3,4,5])
print(arr.shape)
print(arr.dtype)


(5,)
int64


In [44]:
#Reverse a numpy array
reversed_arr = arr[::-1]
print(reversed_arr)



[5 4 3 2 1]


In [45]:
#Extract even numbers from an array

even_numbers = arr[arr % 2 == 0]
print(even_numbers)



[2 4]


In [46]:
#Find the max in each row

arr.max(axis=0)

np.int64(5)

In [47]:
#Compute the mean,std and median of an array

print(arr.mean())

print(np.median(arr))

print(np.std(arr))

3.0
3.0
1.4142135623730951


In [48]:
#Stack two arrays vertically


arr1=np.array([(0,1,2),(1,2,0)])

arr2=np.array([(3,4,5,),(5,4,3)])

np.concatenate((arr1,arr2),axis=0)


array([[0, 1, 2],
       [1, 2, 0],
       [3, 4, 5],
       [5, 4, 3]])

In [49]:
#Stack two arrays horizontally


arr1=np.array([(0,1,2),(1,2,0)])

arr2=np.array([(3,4,5,),(5,4,3)])

np.concatenate((arr1,arr2),axis=1)


array([[0, 1, 2, 3, 4, 5],
       [1, 2, 0, 5, 4, 3]])

In [50]:
#Find the unique values and their counts

unique_values, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_values)
print("Counts:", counts)

Unique values: [1 2 3 4 5]
Counts: [1 1 1 1 1]


In [51]:
#Replace NaN with column means

In [52]:
#Get index of min and max values
min_index = arr.argmin()
max_index = arr.argmax()
print("Index of min value:", min_index)
print("Index of max value:", max_index)



Index of min value: 0
Index of max value: 4


In [53]:
#Create a 3D array of random integers
arr_3d = np.random.randint(0, 10, size=(2, 3, 4))
print(arr_3d)

[[[9 8 9 1]
  [2 7 0 5]
  [1 1 2 4]]

 [[0 4 6 7]
  [3 1 0 9]
  [8 5 1 1]]]


In [54]:
#Use np.where() to replace values


replaced_arr = np.where(arr % 2 == 0, -1, arr)
print(replaced_arr)

[ 1 -1  3 -1  5]


PANDAS

In [55]:
#Create a series using python list

import pandas as pd

series = pd.Series([1, 2, 3, 4, 5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [56]:
#Create a series using custom string indices

series_custom_index = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(series_custom_index)

a    10
b    20
c    30
d    40
dtype: int64


In [57]:
#Create a series from a dictionary
data_dict = {'a': 100, 'b': 200, 'c': 300}
series_from_dict = pd.Series(data_dict)
print(series_from_dict)

a    100
b    200
c    300
dtype: int64


In [58]:
#Access first 3 elements of a series
print(series[:3])


0    1
1    2
2    3
dtype: int64


In [59]:
#Filter series elements greater than 50
filtered_series = series_from_dict[series_from_dict > 50]
print(filtered_series)

a    100
b    200
c    300
dtype: int64


In [60]:
#Add two series with different indices

result = series_custom_index + series_from_dict
print(result)

a    110.0
b    220.0
c    330.0
d      NaN
dtype: float64


In [61]:
#Multiply a series by scalar

multiplied_series = series * 10
print(multiplied_series)



0    10
1    20
2    30
3    40
4    50
dtype: int64


In [62]:
#use multiply () method to multiply with scalar

result=np.multiply(arr,11)

print(result)

[11 22 33 44 55]


In [63]:
#Sort series by value descending
sorted_series = series_from_dict.sort_values(ascending=False)
print(sorted_series)

c    300
b    200
a    100
dtype: int64


In [64]:
#Sort series by index
sorted_by_index=series_from_dict.sort_index()

print(sorted_by_index)


a    100
b    200
c    300
dtype: int64


In [65]:
#Check for null values
print(series.isnull())
print(series_from_dict.isnull())

0    False
1    False
2    False
3    False
4    False
dtype: bool
a    False
b    False
c    False
dtype: bool


In [66]:
#Concatenate two series using concat()

concatenated_series = pd.concat([series, series_custom_index])
print(concatenated_series)


0     1
1     2
2     3
3     4
4     5
a    10
b    20
c    30
d    40
dtype: int64


In [70]:
#Concatenate two series using append()

append=series.append(series_custom_index)

print(append)

AttributeError: 'Series' object has no attribute 'append'

In [71]:
#Retrive first 5 elements using .head()
print(concatenated_series.head())


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [72]:
#Retrive last 5 elements using .tail()

print(concatenated_series.tail())

4     5
a    10
b    20
c    30
d    40
dtype: int64


In [73]:
#Convert series to dataframe

df_from_series = concatenated_series.to_frame(name='values')
print(df_from_series)


   values
0       1
1       2
2       3
3       4
4       5
a      10
b      20
c      30
d      40


In [78]:
#Replace NaN with zero

df=pd.read_excel('2.xlsx',sheet_name='Sheet1')

df

new_df1=df.fillna(00)

print(new_df1)

         Day  Temperature  Windspeed   Event
0 2025-01-01         32.0       45.0   Rainy
1 2025-01-02          0.0       23.0       0
2 2025-01-03         27.0       54.0  Cloudy
3 2025-01-04         23.0       56.0   Sunny
4 2025-01-05          0.0        0.0       0
5 2025-01-06          0.0       56.0   Sunny
6 2025-01-07         19.0       23.0  Cloudy
7 2025-01-08          0.0       78.0   Sunny
8 2025-01-09          0.0       45.0       0


In [79]:
#Drop Missing Values
df_dropped = df.dropna()
print(df_dropped)

         Day  Temperature  Windspeed   Event
0 2025-01-01         32.0       45.0   Rainy
2 2025-01-03         27.0       54.0  Cloudy
3 2025-01-04         23.0       56.0   Sunny
5 2025-01-06          0.0       56.0   Sunny
6 2025-01-07         19.0       23.0  Cloudy


In [80]:
print(concatenated_series.dtype)

int64
